[package]
name = "nospace20"
version = "0.1.0"
authors = ["buyoh <mai@ukibune.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5.0"
